### ISSUE TITLE
Linked List remove item broken

### ISSUE THREAD

**Issue by danjones1618** [datastructures-dev/datastructures-dev.github.io#4]
Says that item is not in list when it is
It then continues on the list to the correct item, highlighting them, but does not remove the item

**Comment by dl1683** [comment]
Can you reproduce it? It works for me

**Comment by danjones1618** [comment]
Add 5 "a" to the front then add 1 "a" to the end then add 3 "an" to the end. Then remove "an"

**Comment by dl1683** [comment]
Figured out the error. It's just the animation time.

**Comment by dl1683** [comment]
Fixed it all
